language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9

# Update pip to the latest version
before_install:
  - python --version
  - pip install -U pip
  - chmod +x script/travis.sh

script:
  - python -m pytest tests/test_json_schema_to_glue_struct.py

deploy:
  provider: pypi
  username: "__token__"
  password: "$PYPI_TOKEN"
  on:
    branch: main