language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - 3.10

# Update pip to the latest version
before_install:
  - python --version
  - pip install -U pip

script:
  - python -m pytest tests/

deploy:
  provider: pypi
  username: "__token__"
  password: "$PYPI_TOKEN"
  skip_existing: true
  on:
    branch: main